tasks:
  deploy-k8s:
    image: lachlanevenson/k8s-kubectl:v1.11.8
    environment:
      name: prod
      cluster:
        name: razorops-cluster
    variables:
      - DOCKER_TAG=${CI_COMMIT_SHA:0:8}
    commands:
      - kubectl -n default set image deployment.v1.apps/web web=docker-image-url:$DOCKER_TAG

workflow:
  - name: production
    tasks: [deploy-k8s]
    when: branch == "main"
